--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/24/2019 2:54:52 PM
-- Server version: 5.5.5-10.1.26-MariaDB
-- Client version: 4.1
--


--
-- Definition for database aparg_test
--
DROP DATABASE IF EXISTS aparg_test;
CREATE DATABASE aparg_test
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE aparg_test;

--
-- Definition for table site_content
--
CREATE TABLE site_content (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Title VARCHAR(255) DEFAULT NULL,
  Content TEXT DEFAULT NULL,
  PID INT(11) DEFAULT NULL,
  Level INT(11) DEFAULT NULL,
  Url VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Dumping data for table site_content
--

-- Table aparg_test.site_content does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;