--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/24/2019 9:40:44 AM
-- Server version: 5.5.5-10.1.26-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';
